### ISSUE TITLE
Is there plan to setup rules to build out debian package besides rpm package?

### ISSUE THREAD

**Issue by changchengx** [intel/idxd-config#1]

**Comment by davejiang** [comment]
Hi Chang Cheng. @dzkdlj is planning to do a new release for Redhat and SLES package pulls soon. Once that gets settled, we can look into adding debian support. Of course contribution is welcome.

**Comment by playaspec** [comment]
I should be easy enough to convert the .rpm into .deb with alien and other such tools. I had no problem converting and running Intel's .rpm based driver suite for the Xeon Phi coprocessor cards on a debian (ubuntu) based system.

**Comment by ramesh-thomas** [comment]
@playaspec thanks for the information. Though rpm to deb conversion tools are useful for installing rpm packages in Ubuntu, I am not sure the deb files generated are in the format acceptable for upload to debian.org. I had been recently working on debian packaging and have created the debian template and tested the package creation. I am currently working on some automation scripts and will publish them shortly.

**Comment by ramesh-thomas** [comment]
Latest accel-config v3.2 release adds debian packaging support. Please refer to README https://github.com/intel/idxd-config#build-debian-package
