### ISSUE TITLE
make kmod dependency optional

### ISSUE THREAD

**Issue by mythi** [intel/idxd-config#10]
We're planning to ship `accel-config` in a container and want to minimize the dependencies needed to be distributed. Since we can control that `accel-config` is only run on systems where `idxd`already loaded, the kmod check is redundant. Can you make the `kmod`dependency a configure option build time?

**Comment by mythi** [comment]
> Are you facing any issue with "make check:" or installation failing?

No. My ask is to be able to say `./configure --disable-kmod-checks` to get `accel-config` without the module check.

> The check is there so it would fail if anyone tries to run it without idxd is loaded and they know why it is failing

In my environment I can check this separately so I can safely skip it with `accel-config`

**Comment by ramesh-thomas** [comment]
The kmod check is done only in the unit test.  When do you see the test getting run without you explicitly running it?  Can you give the commands you are running and the error you see when idxd kernel module is not loaded?

The test will be disabled if you don't include "--enable-test=yes" in the configure command.
If you are generating rpms then use rpmbuild.sh instead of rpmbuild-test.sh

**Comment by ramesh-thomas** [comment]
> in a container and want to minimize the dependencies needed
@mythi  I understand the redundancy of kmod loading idxd but not sure what dependency are you referring to here.  Can you give more details so we can be aware of the issues faced in containers?

Following is my analysis about the redundancy argument:
Currently accel-config uses kmod to load the driver if not loaded and increments the reference count.  I think for accel-config usage which doesn't stay resident, the reference count may not be necessary. It can also check sysfs entry to verify the presence of the kernel module. I prefer removing it altogether as most users would have idxd kernel module loaded.  We can provide an initialization script if necessary to load the driver. @aegl  @davejiang  let me know your opinion.

**Comment by mythi** [comment]
is there a release planned with this change?

**Comment by ramesh-thomas** [comment]
Did not get a chance to do it yet. Will try to make the change after I return from vacation next week.

**Comment by mythi** [comment]
@ramesh-thomas OK, thanks. There seems to be a dependency to udev as well for no obvious reason. Could it be dropped too while we’re at it?

**Comment by ramesh-thomas** [comment]
I will take a look and if not required will remove it. Thanks.

**Comment by ramesh-thomas** [comment]
kmod and udev are removed in new release https://github.com/intel/idxd-config/releases/tag/accel-config-v3.4.3

**Comment by mythi** [comment]
@ramesh-thomas thanks! We'll move to that release ASAP
