### ISSUE TITLE
How to use the dsa as a dma engine?Are there some documents or examples to use dsa in kernel?

### ISSUE THREAD

**Issue by chen982** [intel/idxd-config#12]

**Comment by chen982** [comment]
> https://www.kernel.org/doc/html/latest/driver-api/dmaengine/index.html
> 
> It supports the current DMA engine API when scalable mode (sm_on) is not on. We are working on support for scalable mode.
> 
> You can also take a look at dma_test.c in drivers/dma/ or drivers/ntb/ntb_transport.c for examples.

**Comment by davejiang** [comment]
You can run dmatest with IOMMU in off or on mode. As long as scalable mode is not enabled. idxd_ktest is not public. Please email me directly for any discussion on that. Scalable mode allows KVA usage with SVM support.
