### ISSUE TITLE
Don't put executable binary files in /usr/share

### ISSUE THREAD

**Issue by ColinIanKing** [intel/idxd-config#18]
Currently the test programs are being installed into /usr/share which violates the policy https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrshareArchitectureindependentData and hence lintian complains that these files break the policy with the warning https://lintian.debian.org/tags/arch-dependent-file-in-usr-share

I believe placing them in /usr/lib/accel-config would be the more correct way forward.  This means altering the path in the scripts to match.

**Comment by ramesh-thomas** [comment]
I will move them to /usr/lib/accel-config. I think that is the right folder for the tests. I also looked at /usr/bin but that folder seems to have only executables and not folders containing a set of executables and related data files.

**Comment by ramesh-thomas** [comment]
@ColinIanKing should it go to /usr/lib64/accel-config instead because accel-config is only for 64 bits?

**Comment by ColinIanKing** [comment]
/usr/lib is the default location, but for 64 bit x86 debian multiarch the debhelpers can potentially put it into /usr/lib/x86_64-linux-gnu/

**Comment by ramesh-thomas** [comment]
I will move them to /usr/lib then. I want to keep it common for make install, rpm and debian.

**Comment by snits** [comment]
Should the non test stuff go into /usr/lib/ ? That doesn't seem like a location you would normally look for example configs.
The test/ directory contains the configs it needs, yes?

**Comment by ramesh-thomas** [comment]
> Should the non test stuff go into /usr/lib/ ? That doesn't seem like a location you would normally look for example configs. The test/ directory contains the configs it needs, yes?

Yes, the test programs have their own configs and the sample configs need not be in the same place. I had thought of moving them because the samples themselves were in arbitrary locations. accel-config.conf.sample was in /etc/accel-config and contrib/configs/* was in /usr/share. Also I thought it is better not put things in many different folders.

Should I move accel-config.conf.sample and contrib/configs/* to /usr/share/accel-config and leave the test program and its configs at /usr/lib?  

@davejiang, any opinion?

**Comment by davejiang** [comment]
I thought that typically config files go in /etc? That seems to be the behavior for most Linux apps.

**Comment by snits** [comment]
@ColinIanKing where would Debian normally put the contrib bits?

**Comment by snits** [comment]
On my Fedora system it looks like examples and contrib would normally either be in /usr/share, or /usr/share/doc.

**Comment by xinzhanz** [comment]
On centos, it is installed /usr/lib/accel-config/ with latest change. So it is the last decision to put it under /usr/lib?

**Comment by ramesh-thomas** [comment]
Had a discussion with @davejiang. accel-config is considered a system configuration tool so for that reason /etc seems to be the  appropriate place for the configurations. I will remove the single sample file as it is now redundant and confusing. The ones in contrib/configs are more detailed and address different usage requirements.

**Comment by ColinIanKing** [comment]
/etc is the normal place for configs, generally specific tools/deamons..  have their own directory in /etc for their configs

**Comment by snits** [comment]
Dropping the sample config file from /etc, and moving the contrib configs there works for me.

**Comment by ramesh-thomas** [comment]
This is resolved in 3.5 release https://github.com/intel/idxd-config/releases/tag/accel-config-v3.5.0

**Comment by ramesh-thomas** [comment]
The location of the test folder has changed in the debian upload. It has been changed from /usr/lib to /usr/libexec to use debhelper's default multiarch libdir.  I see that the test script  "test/common" refers to a hardcoded path. How should we resolve this?
1. Make it common for all distributions and place the tests in /usr/libexec/accel-config 
2. Let them be in different locations and the test script checks and uses the path where it finds the test folder

I think #1 is better. Please let me know your opinions.

**Comment by snits** [comment]
I agree, just go with the one location.
