### ISSUE TITLE
Distribution package naming

### ISSUE THREAD

**Issue by snits** [intel/idxd-config#21]
With the recent work being done with Debian support, Is there a plan/desire to change the distro package names from accel-config to idxd-config in the future? I don't remember the history at this point of which name came first. My very hazy recollection is that it was called accel-config before the idxd-config project was added to github. On our end that would mean Jun Miao from Intel re-submitting the package with the new name to Fedora, and then it would find its way into the next RHEL release. I'm not sure if Debian goes through a similar process with a package name change. @ColinIanKing does Debian require re-submission for package name changes?

**Comment by davejiang** [comment]
Most likely not. The package is always been named accel-config. It was unfortunate that when Intel OTC ops created the git repo they named it idxd-config and therefore the git repo is now stuck with that name.

**Comment by snits** [comment]
Good to know. Thanks
