### ISSUE TITLE
iaa_user_test_runner.sh: -flags used twice

### ISSUE THREAD

**Issue by mythi** [intel/idxd-config#22]
Looking at:
https://github.com/intel/idxd-config/blob/a2317b6162baf7d2999b74fdba7e10e65bd339f8/test/iaa_user_test_runner.sh#L93-L94

I can see `-f` is specified twice. Is that expected?

**Comment by ramesh-thomas** [comment]
@xinzhanz Tony, can you take a look?

**Comment by xinzhanz** [comment]
It is not expect, will remove 1.

**Comment by mythi** [comment]
fixed in 3.5.1
