### ISSUE TITLE
Unable to configure workqueue with mdev type

### ISSUE THREAD

**Issue by hueyline** [intel/idxd-config#24]
I was unable to configure workqueue with mdev type. It kept prompting "Invalid argument". 
What are the requirements or steps to enable workqueue with mdev type?

![image](https://user-images.githubusercontent.com/97221497/203836480-0c45a5d1-8663-424a-b5bc-88fddc568892.png)

**Comment by ramesh-thomas** [comment]
mdev is not supported and will be replaced with vdevs. @davejiang, do we still need mdev for internal testing?

**Comment by hueyline** [comment]
@ramesh-thomas  @davejiang  Since mdev is not supported and vdev is not ready yet, how can I create vDSA and pass it to qemu? I am using ubuntu 22.04, kernel 5.15

**Comment by davejiang** [comment]
@hueyline I'm not sure where you are getting mdev support. It is not upstream. It's definitely not in upstream kernel 5.15. If you are using Intel BKC kernel then please move to the 5.19 version. With the introduction of iommufd upstream, we are dropping mdev support for idxd and moving to a new implementation with vdev.

**Comment by ramesh-thomas** [comment]
vdev support is being implemented and tested currently.
