### ISSUE TITLE
accel-config --help is broken

### ISSUE THREAD

**Issue by fenrus75** [intel/idxd-config#32]

**Comment by fenrus75** [comment]
$ accel-config

 usage: accel-config [--version] [--help] COMMAND [ARGS]

.. so far so good, lets use --help

 $ accel-config --help
idxd kernel module not loaded

that's not very --helpful and really not how --help is expected to work

**Comment by ramesh-thomas** [comment]
Posted patch for review
https://lists.linuxfoundation.org/pipermail/accel-config/2023-August/000681.html

**Comment by ramesh-thomas** [comment]
This is resolved in 4.1.1 https://github.com/intel/idxd-config/releases/tag/accel-config-v4.1.1
