### ISSUE TITLE
debian pedantic build is showing up some potential issues that probably need fixing

### ISSUE THREAD

**Issue by ColinIanKing** [intel/idxd-config#34]
Some of the issues are just pedantic C warnings, however there are some issues that probably need some fixes.

Attached is  the -Wpedandic debian build log
[accel-config_4.0-1_amd64.build.log](https://github.com/intel/idxd-config/files/11233046/accel-config_4.0-1_amd64.build.log)

**Comment by ramesh-thomas** [comment]
Posted patch for review
https://lists.linuxfoundation.org/pipermail/accel-config/2023-August/000676.html

**Comment by ramesh-thomas** [comment]
Have also fixed some other compiler warnings I got from latest GCC in Fedora 37 and 38 besides the ones reported in this issue.

**Comment by ramesh-thomas** [comment]
This is resolved in 4.1.1 https://github.com/intel/idxd-config/releases/tag/accel-config-v4.1.1
