### ISSUE TITLE
Invalid driver name error of WQ when enable DSA 

### ISSUE THREAD

**Issue by Sean58238** [intel/idxd-config#40]
We using config file to enable DSA device, and happened an error about "Invalid wq driver name",
Device is enabled, but WQ seems not work.

#  accel-config load-config -c 1e1w-s.conf -e
Warning: "token" attributes are deprecated
Enabling device dsa0
Enabling wq wq0.0
Invalid wq driver name ""
Error enabling wq:q
:

CPU：  Platinum 8455C
IDXD： v4.0

**config file**
[
  {
    "dev":"dsa0",
    "token_limit":0,
    "groups":[
      {
        "dev":"group0.0",
        "tokens_reserved":0,
        "use_token_limit":0,
        "grouped_workqueues":[
          {
            "dev":"wq0.0",
            "mode":"shared",
            "size":128,
            "group_id":0,
            "priority":10,
            "block_on_fault":0,
            "type":"user",
            "name":"app1",
            "threshold":128
          }
        ],
        "grouped_engines":[
          {
            "dev":"engine0.0",
            "group_id":0
          }
        ]
      }
    ]
  }
]

**# accel-config list**
[
  {
    "dev":"dsa0",
    "read_buffer_limit":0,
    "max_groups":4,
    "max_work_queues":8,
    "max_engines":4,
    "work_queue_size":128,
    "numa_node":0,
    "gen_cap":"0x40915f0107",
    "version":"0x100",
    "state":"enabled",
    "max_read_buffers":96,
    "max_batch_size":1024,
    "max_transfer_size":2147483648,
    "configurable":1,
    "pasid_enabled":1,
    "cdev_major":237,
    "clients":0,
    "groups":[
      {
        "dev":"group0.0",
        "read_buffers_reserved":0,
        "use_read_buffer_limit":0,
        "read_buffers_allowed":0,
        "traffic_class_a":1,
        "traffic_class_b":1,
        "grouped_engines":[
          {
            "dev":"engine0.0",
            "group_id":0
          }
        ]
      },
      {
        "dev":"group0.1",
        "read_buffers_reserved":0,
        "use_read_buffer_limit":0,
        "read_buffers_allowed":0,
        "traffic_class_a":1,
        "traffic_class_b":1
      },
      {
        "dev":"group0.2",
        "read_buffers_reserved":0,
        "use_read_buffer_limit":0,
        "read_buffers_allowed":0,
        "traffic_class_a":1,
        "traffic_class_b":1
      },
      {
        "dev":"group0.3",
        "read_buffers_reserved":0,
        "use_read_buffer_limit":0,
        "read_buffers_allowed":0,
        "traffic_class_a":1,
        "traffic_class_b":1
      }
    ],
    "ungrouped_engines":[
      {
        "dev":"engine0.1"
      },
      {
        "dev":"engine0.2"
      },
      {
        "dev":"engine0.3"
      }
    ]
  }
]

**Comment by ramesh-thomas** [comment]
driver_name needs to be specified as follows in the config file.  Please refer to the sample configs in contrib/configs  e.g.  app_profile.conf
"driver_name":"user",

For now user type WQ has only the "user" driver_name. I will add a change to assume that if it is left empty. Meanwhile, please add the driver_name line as done in the sample config file.

**Comment by Sean58238** [comment]
@ramesh-thomas  Thank you!
