### ISSUE TITLE
some questions about idxd driver

### ISSUE THREAD

**Issue by Sean58238** [intel/idxd-config#42]
We have 2 questions about idxd driver as below:
**1.  clients of WQ**
       WQ has a attribute "clients", if an application/workload use this WQ, is the counts of clients will increase 1. And, does any tool can show  which application taking up this device/wq?
**2 device status monitor** 
     How to monitor DSA/IAA workload when it is being used, or in another word, how do we know DSA/IAA is actually working?  Is any tool that can check the device is working in real time?

 Thanks for help!

**Comment by ramesh-thomas** [comment]
>does any tool can show which application taking up this device/wq? 

I don't think driver is storing process ids of applications using devices. @fyu1 can give more info about driver.

>How to monitor DSA/IAA workload when it is being used, or in another word, how do we know DSA/IAA is actually working? Is any tool that can check the device is working in real time?

I don't think there is any way to determine status of operations e.g. data being moved etc. because it is happening inside the hardware.  @fyu1 is there any way to check for busy or "in progress"?

**Comment by fyu1** [comment]
> 1. clients of WQ** WQ has a attribute "clients", if an application/workload use this WQ, is the counts of clients will increase 1. And, does any tool can show which application taking up this device/wq? 

Yes, clients will increase when an app uses the WQ (i.e. open its cdev in user or assign channel in kernel).

There is no tool to show which applications are using WQ. Currently there is no driver snob to show the info. In theory it's doable to show the PIDs info via sysfs if it's useful.

> 2 device status monitor** How to monitor DSA/IAA workload when it is being used, or in another word, how do we know DSA/IAA is actually working? Is any tool that can check the device is working in real time?

Intel PCM tool can monitor DSA/IAA events: https://github.com/intel/pcm.

**Comment by Sean58238** [comment]
Thanks a lot, Intel PCM tool that can helped! :)
