### ISSUE TITLE
test: disable kernel version checks

### ISSUE THREAD

**Issue by mythi** [intel/idxd-config#43]
We are not able to run these tests on RHEL with idxd backported because of
https://github.com/intel/idxd-config/blob/31a0aa67ba09013fa1af517a679d5724f5b8ece9/test/dsa_config_test_runner.sh#L15

Can it be skipped to get the tests run?

**Comment by davejiang** [comment]
Probably. Does RHEL support IOMMU scalable mode (sm_on) now? This issue should be reported to Redhat as it's an issue against their kernel version for their distro. As bypass, you can manually set the environmental KVER variable for running the script.

**Comment by mythi** [comment]
> As bypass, you can manually set the environmental KVER variable for running the script.

that's a good tip, I did not read the script carefully enough. I'll pass it on to the team. Not directly working on this myself, so the IOMMU question I can't answer sorry.

**Comment by mregmi** [comment]
We are testing this in RHCOS (OpenShift). We do have sm_on enabled. We will look into how we can set KVER.

**Comment by davejiang** [comment]
KVER=x.y.z ./test-script

**Comment by mregmi** [comment]
This workaround worked for us. Thanks.
I wonder what would be a proper fix instead of tricking the script. Might be an issue for our RHEL 8.X based releases. RHEL 9.x should be good as they are using 5.14.x

**Comment by davejiang** [comment]
The upstream source can't be responsible to keep track of OSV kernel versions. Otherwise it would quickly get out of hand. We only support kernel.org kernels. It's up to the OSV, in this case Redhat, to provide additional modifications that applies to their distro. You can try open a BUGZILLA entry against RHEL.

**Comment by mythi** [comment]
> in this case Redhat, to provide additional modifications that applies to their distro

It's worth pointing out that in our use case with containers this isn't the case: we build a container following releases in this repo and it's expected to run regardless of what the kernel version when given the the WQs to it

**Comment by hershpa** [comment]
> Probably. Does RHEL support IOMMU scalable mode (sm_on) now? This issue should be reported to Redhat as it's an issue against their kernel version for their distro. As bypass, you can manually set the environmental KVER variable for running the script.

Yes, RHEL8.6 based OpenShift 4.12 RHCOS does support it and we enable `intel_iommu=on,sm_on` as as kernel boot parameter.
