### ISSUE TITLE
Unable to configure IAA device

### ISSUE THREAD

**Issue by raunaks13** [intel/idxd-config#45]
I built the project successfully and ran:
```
$ sudo accel-config load-config -c contrib/configs/app_profile.conf -e
libaccfg: accfg_wq_set_str_mode: wq0.0: write failed: Invalid argument
wq set mode value failed
Parse json and set device fail: -1
```
However I am getting this error. I also tried configuring the device via QPL but I am getting a similar error.

**Comment by ramesh-thomas** [comment]
Did you change contrib/configs/app_profile.conf? The error states that mode is being set to "wq0.0" which is obviously invalid. Mode is either "shared" or "dedicated".

**Comment by ramesh-thomas** [comment]
Assuming this is resolved.
