### ISSUE TITLE
accel-config load-config failure with max_batch_size on iax devices

### ISSUE THREAD

**Issue by snits** [intel/idxd-config#59]
Saving the config that is set up with the defaults for iax devices, disabling the iax wqs and devices, and then doing accel-config load-config with that saved config fails with:

```
# accel-config load-config -c test.config 
libaccfg: accfg_wq_set_max_batch_size: wq1.0: max_batch_size attribute write failed: No such file or directory
wq set max_batch_size value failed
Parse json and set device fail: -1
```

accel-config list shows the following for max batch size for the iax devices:

            "max_batch_size":-2,

The iax devices and wqs have no max_batch_size entry under sysfs.

I haven't dug into the code yet, but I imagine there needs to be something sanity checking the value being sent to sysfs as I'm sure that -2 wouldn't work if the file did exist, and also deal with the case where the cap isn't available when listing the config and saving?

This is with 4.1.6.

**Comment by ramesh-thomas** [comment]
@snits thanks for reporting this issue. I have pushed a patch https://github.com/intel/idxd-config/commit/ea015cc437e6acc4b1c22e50444567fc5a8f5052 in the pending branch that addresses this issue.  Can you please verify if it fixes the issue? Thanks.

**Comment by snits** [comment]
I will try to grab a system and test it later today.

**Comment by snits** [comment]
Sorry, I still havent't got to this. I will test it today.

@ramesh-thomas Now that [Intel-SA-01084](https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-01084.html) is disclosed, do you have plans to modify the test code to test the write op as well as the mmap op?

**Comment by snits** [comment]
@ramesh-thomas patch worked for me.

Tested-by: Jerry Snitselaar <jsnitsel@redhat.com>
Reviewed-by: Jerry Snitselaar <jsnitsel@redhat.com>

**Comment by ramesh-thomas** [comment]
> @ramesh-thomas Now that [Intel-SA-01084](https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-01084.html) is disclosed, do you have plans to modify the test code to test the write op as well as the mmap op?

I am looking into this. I am wondering whether accel-config needs any change as the purpose of the tests are to test the DSA/IAA feature only and can be run using the current mmap implementation in root mode.

@ysun please take a look

**Comment by snits** [comment]
Possibly not. I use the tests to also help test things when I backport changes for the idxd driver to make sure the tests are still running and passing, so it would be nice to have in there, but I can also come up with something else.

**Comment by ramesh-thomas** [comment]
> Possibly not. I use the tests to also help test things when I backport changes for the idxd driver to make sure the tests are still running and passing, so it would be nice to have in there, but I can also come up with something else.

As mentioned in the disclosure, trusted software will not be blocked i.e. you can continue to use mmap as being done currently in the tests. 

@fenrus75 FYI.

**Comment by snits** [comment]
I understand that, but I also need to test that the write op is actually working. I will work on something separate.

**Comment by ysun** [comment]
> > @ramesh-thomas Now that [Intel-SA-01084](https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-01084.html) is disclosed, do you have plans to modify the test code to test the write op as well as the mmap op?
> 
> I am looking into this. I am wondering whether accel-config needs any change as the purpose of the tests are to test the DSA/IAA feature only and can be run using the current mmap implementation in root mode.
> 
> @ysun please take a look

OK, I'll take a look, but I'm not in a rush. I've been busy recently with enabling new OP codes for DSA3.

**Comment by ramesh-thomas** [comment]
> I understand that, but I also need to test that the write op is actually working. I will work on something separate.

@snits @ysun or someone in his team would be implementing this change in the accel-config tests once the idxd changes are finalized.
